#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'


cookbook 'yum'
#cookbook 'apt'

cookbook 'newrelic',
        :git => 'https://github.com/escapestudios/chef-newrelic.git',
        :ref => 'master'
cookbook 'mysql'
cookbook 'chef-solo-search'


#chef-solo-demo
cookbook 'nginx'
cookbook 'iptables'
        
