# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BASE_DIR = File.dirname(__FILE__)
NAME = "ex05"
CENTOS65_URL = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "CentOS 6.4 x86_64"
  config.vm.box_url = CENTOS65_URL
  config.vm.network "private_network", ip: "192.168.56.80"
  config.vm.hostname = "#{NAME}"

  config.vm.provider :virtualbox do |vb|
    vb.customize [ "modifyvm", :id, "--memory", "512"]
    vb.name = "#{NAME}"
  end
  config.librarian_chef.cheffile_dir = "."
  #config.vm.provision :shell, :path => File.expand_path("install-chef-client.sh", __FILE__)
  config.vm.provision "shell",
    inline: "[[ `which chef-solo` ]] || curl -L https://www.opscode.com/chef/install.sh | sudo bash"
  config.vm.provision :chef_solo do |chef|
          chef.cookbooks_path = [ "chef/cookbooks", "chef/site-cookbooks"]
          chef.roles_path     = ["roles"]
          chef.log_level      = ENV['CHEF_LOG'] ? ENV['CHEF_LOG'].to_sym : :info
          chef.add_recipe "web"
	  chef.json = { some_key: "value" }
  end

end
